name: Pipeline

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  construccion:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Construir
      working-directory: ${{github.workspace}}
      shell: bash
      run: ./scripts/build.sh -t

    - name: Pruebas
      working-directory: ${{github.workspace}}
      shell: bash
      run: ./scripts/test.sh -nb

  publicar-documentacion:
    runs-on: ubuntu-latest
    needs: construccion
    steps:
    - uses: actions/checkout@v2

    - name: Generar configuracion
      working-directory: ${{github.workspace}}
      shell: bash
      run: |
        chmod +x ./scripts/generar-documentacion.sh
        ./scripts/generar-documentacion.sh

    - name: Publica en Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./documentacion

  versionado:
    runs-on: ubuntu-latest
    needs: construccion
    env:
      MENSAJE_COMMIT: ${{ github.event.head_commit.message }}
    steps:
      - if: "!startsWith(github.event.head_commit.message, '[VERSION]')"
      - uses: actions/checkout@v2
      - name: Generar version
        working-directory: ${{github.workspace}}
        shell: bash
        run: |
          chmod +x ./scripts/versionar.sh ./scripts/liberar-version.sh
          ./scripts/liberar-version.sh "${MENSAJE_COMMIT}"