name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      working-directory: ${{github.workspace}}
      shell: bash
      run: ./scripts/build.sh

    - name: Test
      working-directory: ${{github.workspace}}
      shell: bash
      run: ./scripts/test.sh

    - name: Generar configuracion
      working-directory: ${{github.workspace}}
      shell: bash
      run: |
        chmod +x ./scripts/generar-documentacion.sh
        ./scripts/generar-documentacion.sh

    - name: Push changes
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./documentacion/html
