name: Pipeline

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  construccion:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Construir
      working-directory: ${{github.workspace}}
      shell: bash
      run: ./scripts/build.sh

    - name: Pruebas
      working-directory: ${{github.workspace}}
      shell: bash
      run: ./scripts/test.sh

  publicar-documentacion:
    runs-on: ubuntu-latest
    needs: construccion
    steps:
    - uses: actions/checkout@v2

    - name: Generar configuracion
      working-directory: ${{github.workspace}}
      shell: bash
      run: |
        chmod +x ./scripts/generar-documentacion.sh
        ./scripts/generar-documentacion.sh

    - name: Publica en Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./documentacion
